# Use the official PHP 8.2 FPM image, which is based on Debian
FROM php:8.2-fpm

WORKDIR /var/www/html

# Install the extension manager
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# Install all extensions cleanly
RUN install-php-extensions \
    amqp \
    bcmath \
    exif \
    gd \
    imagick \
    intl \
    memcached \
    opcache \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    redis \
    soap \
    sockets \
    xsl \
    zip

# Configure PHP settings & set up non-root user (Debian uses groupadd / useradd)
ARG PUID=1000
ARG PGID=1000
RUN echo "memory_limit=4096M" > /usr/local/etc/php/conf.d/memory-limit.ini \
    && groupadd -g ${PGID} laravel \
    && useradd -u ${PUID} -g laravel -s /bin/bash -m laravel

# Switch to the non-root user
USER laravel

# Install Composer cleanly
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
